aves/urls.py
from django.urls import path

from . import views

from django.views.generic import RedirectView
from django.urls import reverse_lazy

app_name = 'aves'

urlpatterns = [
    path( '',RedirectView.as_view( url = reverse_lazy( 'aves:ave_list' )), name = 'index' ),

    #Aves
    path( 'ave_list/', views.AveListView.as_view(), name = 'ave_list' ),
    path( 'ave/create/', views.AveCreateView.as_view(), name = 'ave_create' ),
    path( 'ave/<int:pk>/edit/', views.AveEditView.as_view(), name = 'ave_edit' ),
    path( 'ave/<int:pk>/detail/', views.AveDetailView.as_view(), name = 'ave_detail' ),
    path( 'ave/<int:pk>/delete/', views.AveDeleteView.as_view(), name = 'ave_delete' ),

    #Ordem
    path( 'ordem/ordem_list/', views.OrdemListView.as_view(), name = 'ordem_list' ),
    path( 'ordem/create/', views.OrdemCreateView.as_view(), name = 'ordem_create' ),
    path( 'ordem/<int:pk>/edit/', views.OrdemEditView.as_view(), name = 'ordem_edit' ),    
    path( 'ordem/<int:pk>/delete/', views.OrdemDeleteView.as_view(), name = 'ordem_delete' ),

    #Classificação
    path( 'classifi/classifi_list/', views.ClassifiExtraListView.as_view(), name = 'classifi_list' ),
    path( 'classifi/create/', views.ClassifiExtraCreateView.as_view(), name = 'classifi_create' ),
    path( 'classifi/<int:pk>/edit/', views.ClassifiExtraEditView.as_view(), name = 'classifi_edit' ),    
    path( 'classifi/<int:pk>/delete/', views.ClassifiExtraDeleteView.as_view(), name = 'classifi_delete' ),
    
]

avessite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path( '', RedirectView.as_view( url = '/aves/' ), name = 'index' ),
    path( 'aves/', include( 'aves.urls' )),
]

aves/models.py
from django.db import models

from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse


_BigCharField = 2048 #para não ter que configurar o tamanho de tudo


def pick_val_in_choice( choice_tpl, choice_val ):
    """Gambiara para pegar valor em lista de tupla de choice."""
    choice_val = choice_val.strip().casefold()
    for key, val in choice_tpl:
        if key.casefold() == choice_val:
            return val

    return None


def choice_from_display_name( choice_tpl, search_display ):
    """Gambiarra para pegar as escolhas pelo nome de display"""
    search_display = search_display.strip().casefold()
    rev = [ ( display_name.strip().casefold(), choice )
            for choice, display_name
            in choice_tpl ]
    return pick_val_in_choice( rev, search_display )


class Ave( models.Model ):
    """Modelo de Aves."""
    
    nome_cientifico = models.CharField( 'nome científico',
                                        max_length = _BigCharField,
                                        unique = True )

    def clean_nome_cientifico( self ):
        return self.cleaned_data[ 'nome_cientifico' ].strip().capitalize()

    autor = models.CharField( 'nome do autor',
                              max_length = _BigCharField,
                              null = True,
                              blank = True )
    def clean_autor( self ):
        return self.cleaned_data[ 'autor' ].strip().replace( '(', '' ).replace( ')', '' ).capitalize()
    
    nome_popular = models.CharField( 'nome popular',
                                     max_length = _BigCharField,
                                     null = True,
                                     blank = True )

    def clean_nome_popular( self ):
        return self.cleaned_data[ 'nome_popular' ].strip().capitalize()

    nome_ingles = models.CharField( 'nome em inglês',
                                    max_length = _BigCharField,
                                    blank = True,
                                    null = True )

    familia = models.ForeignKey( 'familia',
                                 verbose_name = 'família',
                                 on_delete = models.SET_NULL,
                                 null = True,
                                 blank = True )

    frequencia_ocorrencia = models.IntegerField( 'frequência de ocorrência',
                                                 null = True,
                                                 blank = True )
    abundancia_relativa = models.CharField( 'abundância relativa',
                                            max_length = 2,
                                            null = True,
                                            blank = True )    
    
    ESTADOS_CONSERVACAO = (
        ( 'LC', 'Pouco Preocupante' ),
        ( 'NT', 'Quase Ameaçada' ),
        ( 'VU', 'Vulnerável' ),
        ( 'EN', 'Em Perigo' ),
        ( 'CR', 'Criticamente em Perigo' ),
        ( 'EW', 'Extinta na Natureza', ),
        ( 'EX', 'Extinta' ),
        ( 'DD', 'Dados Insuficientes', ),
        ( 'NE', 'Não Avaliada', ),
    )

    ESTADOS_CONSERVACAO_EN = (
        ( 'LC', 'Least Concern' ),
        ( 'NT', 'Near Threatened' ),
        ( 'VU', 'Vulnerable' ),
        ( 'EN', 'Endangered' ),
        ( 'CR', 'Critically Endangered' ),
        ( 'EW', 'Extinct in The Wild' ),
        ( 'EX', 'Extinct' ),
        ( 'DD', 'Data Deficient' ),
        ( 'NE', 'Not Evaluated' ),
    )

    ESTADOS_CONSERVACAO_IMG = (
        ( 'LC', 'aves/iucn/LC.png' ),
        ( 'NT', 'aves/iucn/NT.png' ),
        ( 'VU', 'aves/iucn/VU.png' ),
        ( 'EN', 'aves/iucn/EN.png' ),
        ( 'CR', 'aves/iucn/CR.png' ),
        ( 'EW', 'aves/iucn/EW.png' ),
        ( 'EX', 'aves/iucn/EX.png' ),
        ( 'DD', 'aves/iucn/DD.png' ),
        ( 'NE', 'aves/iucn/NE.png' ),
    )    

    def pick_iucn_sp_img( self ):
        """Pega o caminho para a imagem do estado de conservação..."""
        return pick_val_in_choice( self.ESTADOS_CONSERVACAO_IMG, self.estado_iucn_sp )

    def pick_iucn_int_img( self ):
        """Pega o caminho para a imagem do estado de conservação..."""
        return pick_val_in_choice( self.ESTADOS_CONSERVACAO_IMG, self.estado_iucn_int )

    estado_iucn_sp = models.CharField( 'estado de conservação em São Paulo',
                                       max_length = 2,
                                       choices = ESTADOS_CONSERVACAO,
                                       null = True,
                                       blank = True )

    estado_iucn_int = models.CharField( 'estado de conservação Internacional',
                                        max_length = 2,
                                        choices = ESTADOS_CONSERVACAO,
                                        null = True,
                                        blank = True )

    info = models.TextField( 'informações gerais', blank = True )
    
    imagem_capa = models.ImageField( 'imagem de capa', null = True, blank = True )


    def __str__( self ):
        return self.nome_cientifico

    
    def nome_especie( self ):
        """Retorna o nome 'Subfamília Espécie' como 'S. espécie'.
        Se tiver menos de duas palavras no nome retorna o nome como title"""
        spli = self.nome_cientifico.lower().strip().split()
        if len( spli ) < 2:
            return self.nome_cientifico.strip().title()
        else:
            spli[ 0 ] = spli[ 0 ][ :1 ].title() + '.'
            return ' '.join( spli )

    
    def subfamilia( self ):
        """Separa subfamilia do nome científico."""
        spli = self.nome_cientifico.strip().lower().split()
        if len( spli ) < 2:
            return ''
        else:
            return spli[ 0 ].title()
    

    def get_absolute_url( self ):
        return reverse( 'aves:ave_detail', args = [ self.pk ])
    
    class Meta:
        ordering = [ 'nome_cientifico' ]



        
# @receiver( pre_save, sender = Ave )
# def create_pre_save( sender, instance, *args, **kwargs ):
#     """Arruma os campos antes de salvar."""
#     instance.nome_cientifico = instance.nome_cientifico.capitalize()
# #   if instance.nome_popular:
# #       instance.nome_popular = instance.nome_popular.capitalize()
#     if instance.autor:
#         instance.autor = instance.autor.replace( '(', '' ).replace( ')', '' ).strip().capitalize()


    
        
class InfoExtra( models.Model ):
    """Capos extras com informações de texto de aves.
    Exemplo: Alimentação, reprodução, sub-espécies, habitos...
    Modelo Ave tem um campo de informações gerais."""
    
    ave = models.ForeignKey( Ave, on_delete = models.CASCADE )
    titulo = models.CharField( 'título', max_length = _BigCharField )
    texto = models.TextField()

    class Meta:
        verbose_name = 'informação extra'
        verbose_name_plural = 'informações extras'

    def __str__( self ):
        return f"{self.ave.nome_cientifico}: {self.titulo}"


class FotoAve( models.Model ):
    """Fotos extras para as aves.
    Modelo Ave tem um campo para imagem de capa."""
    
    ave = models.ForeignKey( Ave, on_delete = models.CASCADE )
    imagem = models.ImageField()
    leganda = models.CharField( max_length = _BigCharField, blank = True )
        
    def __str__( self ):
        return f"Foto #{self.id} de {self.ave.nome_cientifico}"

    class Meta:
        verbose_name = "foto de ave"
        verbose_name_plural = "fotos de aves"


class ClassifiExtra( models.Model ):
    """Campos extras para classificação de taxonomia."""
    reino = models.CharField( max_length = _BigCharField,
                              blank = True,
                              null = True )
    filo = models.CharField( max_length = _BigCharField,
                                    blank = True,
                                    null = True )
    classe = models.CharField( max_length = _BigCharField )

    class Meta:
        ordering = [ 'classe' ]
        verbose_name = 'classificação extra'
        verbose_name_plural = 'classificações estras'

    def __str__( self ):
        def nod( s ):
            """Name or dash."""
            return s if s != '' else '---'
        
        return f"Classe: {nod(self.classe)}; Filo: {nod(self.filo)}; Reino: {nod(self.reino)}"

    def familia_count( self ):
        """Conta quantidade total de famílias nas ordens."""
        s = 0
        for ordem in self.ordem_set.all():
            s += ordem.familia_set.count()
        return s

    def aves_count( self ):
        """Conta quantidade total de avess dentro desta classificação."""
        s = 0
        for ordem in self.ordem_set.all():
            s += ordem.quantidade_aves()
        return s
    

        
class Ordem( models.Model ):
    classifiextra = models.ForeignKey( ClassifiExtra,
                                       verbose_name = 'classificação extra',
                                       null = True,
                                       blank = True,
                                       on_delete = models.SET_NULL )
    
    nome = models.CharField( max_length = _BigCharField, unique = True )

    class Meta:
        verbose_name_plural = 'ordens'
        ordering = [ 'nome' ]

    def __str__( self ):
        return self.nome.title()

    def quantidade_aves( self ):
        """Quantidade de aves em todas as famílias pertencentes a esta ordem."""
        s = 0
        for fam in self.familia_set.all():
            s += fam.ave_set.count()

        return s
        

    



class Familia( models.Model ):
    ordem = models.ForeignKey( Ordem, on_delete = models.CASCADE )
    
    nome = models.CharField( max_length = _BigCharField, unique = True )
    autor = models.CharField( max_length = _BigCharField, null = True, blank = True )

    class Meta:
        verbose_name = 'família'
        ordering = [ 'nome' ]

    def __str__( self ):
        return self.nome.title()
    
   

aves/views.py
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy

from .models import Ave, InfoExtra, FotoAve, Familia, Ordem, ClassifiExtra

from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from django.views import View

from django.contrib.messages.views import SuccessMessageMixin

from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetView, NamedFormsetsMixin, NamedFormsetsMixin, InlineFormSetFactory, SearchableListMixin



# Aves
class AveView( View ):
    """View de aves. Para não ter que por o Model em todas as views normais."""
    model = Ave


class AveListView( SearchableListMixin, AveView, ListView ):
    #template='ave/ave_list.html'
    search_fields = [ 'nome_cientifico', 'nome_popular' ]
    pass


class AveDetailView( AveView, DetailView ):
    #template='ave/ave_detail.html'
    pass


class AveDeleteView( SuccessMessageMixin, AveView, DeleteView ):
    #template='ave/ave_confirm_delete.html'
    success_url = reverse_lazy( 'aves:ave_list' )

    def get_success_message( self, cleaned_data ):
        """Gambiarra para retornar mensagem de sucesso com o objeto já exclúido."""
        return f"Ave \"{self.object}\" foi removida com sucesso!"
    

class InfoExtraInline( InlineFormSetFactory ):
    model = InfoExtra
    fields = '__all__'


class FotoAveInline( InlineFormSetFactory ):
    model = FotoAve
    fields = '__all__'


class AveCreateView( NamedFormsetsMixin, SuccessMessageMixin, AveView, CreateWithInlinesView ):
    #template='ave/ave_form.html'
    success_message = "Ave \"%(nome_cientifico)s\" foi inclúida com sucesso!"
    #success_url = reverse_lazy( 'aves:ave_list' )
    #success_url = reverse( 'aves:ave_detail' ...
    fields = (
        'nome_cientifico',
        'autor',
        'nome_popular',
        'nome_ingles',
        'familia',
        'imagem_capa',
        'estado_iucn_sp',
        'estado_iucn_int',
        'frequencia_ocorrencia',
        'abundancia_relativa',
        'info',
    )
    inlines = [ InfoExtraInline, FotoAveInline ]
    inlines_names = [ 'infoextra_inline', 'fotoave_inline' ]




class AveEditView( NamedFormsetsMixin, SuccessMessageMixin, AveView, UpdateWithInlinesView ):
    #template='ave/ave_form.html'
    success_message = "Ave \"%(nome_cientifico)s\" foi editada com sucesso!"
    #success_url = reverse_lazy( 'aves:ave_list' )
    #success_url = reverse( 'aves:ave_detail' ...    
    fields = (
        'nome_cientifico',
        'autor',
        'nome_popular',
        'nome_ingles',
        'familia',
        'imagem_capa',
        'estado_iucn_sp',
        'estado_iucn_int',
        'frequencia_ocorrencia',
        'abundancia_relativa',
        'info',
    )
    inlines = [ InfoExtraInline, FotoAveInline ]
    inlines_names = [ 'infoextra_inline', 'fotoave_inline' ]
    

        


#Taxonomia
class FamiliaInLine( InlineFormSetFactory ):
    model = Familia
    fields = '__all__'
    factory_kwargs = { 'extra': 20 }

    
class OrdemView( View ):
    model = Ordem


class OrdemListView( OrdemView, ListView ):
    #template='ave/ordem_list.html'
    pass


class OrdemCreateView( NamedFormsetsMixin, SuccessMessageMixin, OrdemView, CreateWithInlinesView ):
    #template='ave/ordem_form.html'
    success_message = "Ordem \"%(nome)s\" foin incúida com sucesso!"
    success_url = reverse_lazy( 'aves:ordem_list' )
    fields = '__all__'
    inlines = [ FamiliaInLine ]
    inlines_names = [ 'familia_inline' ]


class OrdemEditView( NamedFormsetsMixin, SuccessMessageMixin, OrdemView, UpdateWithInlinesView ):
    success_message = "Ordem \"%(nome)s\" foi editada com sucesso!"
    success_url = reverse_lazy( 'aves:ordem_list' )
    fields = '__all__'
    inlines = [ FamiliaInLine ]
    inlines_names = [ 'familia_inline' ]    
    


class OrdemDeleteView( SuccessMessageMixin, OrdemView, DeleteView ):
    #template='ave/ordem_confirm_delete.html'
    success_url = reverse_lazy( 'aves:ordem_list' )

    def get_success_message( self, cleaned_data ):
        return f"Ordem \"{self.object}\" foi removida com sucesso!"


#ClassifiExtra
class ClassifiExtraView( View ):
    model = ClassifiExtra

class ClassifiExtraListView( ClassifiExtraView, ListView ):
    #template='ave/classifiextra_list.html'
    pass

class ClassifiExtraCreateView( SuccessMessageMixin, ClassifiExtraView, CreateView ):
    #template='ave/classifiextra_form.html'
    def get_success_message( self, cleaned_data ):
        return f"Classificação \"{self.object}\" foi criada com sucesso!"        
    success_url = reverse_lazy( 'aves:classifi_list' )
    fields = '__all__'


class ClassifiExtraEditView( SuccessMessageMixin, ClassifiExtraView, UpdateView ):
    #template='ave/classifiextra_form.html'
    
    def get_success_message( self, cleaned_data ):
        return f"Classificação \"{self.object}\" foi editada com sucesso!"    

    success_url = reverse_lazy( 'aves:classifi_list' )
    fields = '__all__'
    

class ClassifiExtraDeleteView( SuccessMessageMixin, ClassifiExtraView, DeleteView ):
    #template='ave/ordem_confirm_delete.html'
    success_url = reverse_lazy( 'aves:classifi_list' )

    def get_success_message( self, cleaned_data ):
        return f"Classificação \"{self.object}\" foi removida com sucesso!"
    

aves/templates/aves/ave_detail.html
{% extends 'aves/base.html' %}

{% load static %}

{% block title %}Detalhes de {{ ave.nome_cientifico }}{% endblock %}

{% block main_content %}
<article>
  <section class="card">
    <div class = "row">
      
      {% if ave.imagem_capa %}
      <div class="col-md-6 p-3">

	<img src="{{ ave.imagem_capa.url }}" alt="Foto de capa da ave {{ ave.nome_cientifico }}" class="card-img img-thumbnail img-fluid float-start">
      </div>
      {% endif %}
      
      
      {% if ave.imagem_capa %}
      <div class="col-md-6">
      {% else %}
      <div class="col-md-12">
      {% endif %}

      <section class="card-body">
	    
	    <h2 class="card-title">{{ ave.nome_cientifico }}</h2>
	    {% if ave.autor and ave.autor.split != '' %}
	    <h5 class="card-subtitle text-muted"><em>{{ ave.autor }}</em></h5>
	    {% endif %}
	    
	    {% if ave.nome_popular %}
	    <hr>

	    <h2 class="card-title">{{ ave.nome_popular }}</h2>
	    {% endif %}
	    

	    {% if ave.nome_ingles%}
	    <h5><strong>Nome em Inglês:</strong> {{ nome.ingles }}</h5>
	    {% endif %}
	    

	    <hr>

	    <h2 class="card-title">Classificação Ciêntifica</h2>

	    <div class="table-responsive">
	      <table class="table">

		{% with classi=ave.familia.ordem.classifiextra %}
		{% if classi %}
		<tr>
		  <th scope="row">Reino:</th>
		  
		  <td>{{ classi.reino | default:'&mdash;' }}</td>
		</tr>

		<tr>
		  <th scope="row">Filo:</th>
		  
		  <td>{{ classi.filo | default:'&mdash;' }}</td>
		</tr>	
		
		<tr>
		  <th scope="row">Classe:</th>
		  
		  <td>{{ classi.classe | default:'&mdash;' }}</td>
		</tr>	
		
		{% endif %}
		{% endwith %}

		<tr>
		  <th scope="row">Ordem:</th>
		  
		  <td>{{ ave.familia.ordem.nome | default:'&mdash;' }}</td>
		</tr>	

		<tr>
		  <th scope="row">Família:</th>
		  
		  <td>
		    {{ ave.familia.nome | default:'&mdash;' }}
		    {% if ave.familia.autor %}
		    <br>
		    <p class="text-muted">({{ ave.familia.autor }})</p>
		    {% endif %}
		  </td>

		  
		</tr>	

		<tr>
		  <th scope="row">Subfamília:</th>
		  
		  <td>{{ ave.subfamilia | default:'&mdash;' }}</td>
		</tr>

		<tr>
		  <th scope="row">Espécie:</th>
		  
		  <td>{{ ave.nome_especie }}
		    {% if ave.autor %}
		    <br>
		    <p class="text-muted">({{ ave.autor }})</p>
		    {% endif %}
		  </td>
		</tr>

	      </table>


	    </div>
	    
	  </section>
	  
	</div>	
      </div>
  </section>

  {% if ave.info %}
  <section class="card my-3">
    <div class="card-body">

	<h2 class="card-title">Informações Gerais</h2>
	<p class="cad-text">
	  {{ ave.info | linebreaks }}
	</p>


    </div>

  </section>
  {% endif %}

  <section class="row">
  {% if ave.estado_iucn_int %}
  <article class="my-3 p-3 col-lg-6">
    <div class="card-body">
      <h2 class="card-title">Estado de Conservação Internacional</h2>

      <figure class="figure">
	<img class="figure-img img-fluid mw-50 mh-50" src="{% static ave.pick_iucn_int_img %}" alt="Imagem do estado de conservação {{ ave.get_estado_iucn_int_display }}">
	<figcaption class="figure-caption">{{ ave.get_estado_iucn_int_display }}</figcaption>
      </figure>
      
    </div>

  </article>
  {% endif %}


  {% if ave.estado_iucn_sp %}
  <article class="my-3 p-3 col-lg-6">
    <div class="card-body">
      <h2 class="card-title">Estado de Conservação em São Paulo</h2>

      <figure class="figure">
	<img class="figure-img img-fluid mw-50 mh-50" src="{% static ave.pick_iucn_sp_img %}" alt="Imagem do estado de conservação {{ ave.get_estado_iucn_sp_display }}">
	<figcaption class="figure-caption">{{ ave.get_estado_iucn_sp_display }}</figcaption>
      </figure>
      
    </div>

  </article>
  {% endif %}

</section>  

  {% with infos=ave.infoextra_set.all %}
  {% for info in infos %}
  <section class="card my-3">
    <div class="card-body">

	<h2 class="card-title">{{ info.titulo }}</h2>
	<p class="cad-text">
	  {{ info.texto | linebreaks }}
	</p>


    </div>

  </section>  
  {% endfor %}
  {% endwith %}

  {% with fotos=ave.fotoave_set.all %}
  {% if fotos %}
  <div class="card border my-3">
    <div class="col-md-12 m-3">
      <h2>Imagens</h2>
      {% for foto in fotos %}
      <div class="text-center my-3">
	<figure class="figure">
	  <img src="{{ foto.imagem.url }}" alt="{{ foto }}" class="figure-img img-fluid">
	  <figcaption class="figure-caption">{{ foto.legenda }}</figcaption>
	</figure>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}
  {% endwith %}


  
  <section class="d-flex flex-row-reverse my-3">
    <div class="btn-group">
      <a class="btn btn-warning" role="button" alt="Editar" data-bs-toggle="tooltip" data-bs-original-title="Editar" href="{% url 'aves:ave_edit' ave.pk %}">
	Editar <i class="bi bi-pencil"></i>
      </a>
      <a class="btn btn-danger rem-btn" data-ave-nome="Dendrocygna bicolor" role="button" alt="Remover" data-bs-toggle="tooltip" data-bs-original-title="Remover" href="{% url 'aves:ave_delete' ave.pk %}">
	Remover <i class="bi bi-trash"></i>		
      </a>
    </div>  
  </section>

</article>

{% endblock %}

aves/templates/aves/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
  <html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">    
    {% block extra_header %}
    {% endblock %}

    <title>{% block title %}Página Inicial{% endblock %} &mdash; Projeto Aves</title>
  </head>
  <body>

    <!-- https://getbootstrap.com/docs/5.0/components/navbar/ -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
	<a class="navbar-brand" href="{% url 'aves:index' %}">Projetos Aves</a>

	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
	
	<div class="collapse navbar-collapse" id="navbarScroll">
	  <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Página Inicial</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
		Aves
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
		<li><a class="dropdown-item" href="{% url 'aves:ave_list' %}">Lista de Aves</a></li>
		<li><a class="dropdown-item" href="{% url 'aves:ave_create' %}">Nova Ave</a></li>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
		Classificação
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
		<li><a class="dropdown-item" href="{% url 'aves:ordem_list' %}">Ordens e Famílias</a></li>
		<li><a class="dropdown-item" href="{% url 'aves:ordem_create' %}">Nova Ordem/Famílias</a></li>
		<li><hr class="dropdown-divider"></li>
		<li><a class="dropdown-item" href="{% url 'aves:classifi_list' %}">Reinos/Filos/Classes</a></li>
		<li><a class="dropdown-item" href="{% url 'aves:classifi_create' %}">Novo Reino/Filo/Classe</a></li>				
              </ul>
            </li>
	    
	    
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin</a>
            </li>
	    
	  </ul>
	  <form class="d-flex" method="GET" action="{% url 'aves:ave_list' %}">
            <input class="form-control me-2" type="search" placeholder="Pesquisar por ave" aria-label="Search" name="q">
            <button class="btn btn-success" type="Pesquisar">Pesquisar</button>
	  </form>
	</div>
      </div>
    </nav>

    
    <main class="container p-3">
      <section>
      {% bootstrap_messages %}
      </section>
      
      {% block main_content %}
      {% endblock %}
      
    </main>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% block end_body_script %}
    {% endblock %}
    
  </body>
</html>